[
  {
    "img": "https://i.ibb.co/vZNphzc/icon1-1.jpg",
    "courseTitle": "Introduction to Web Development",
    "name": "John Doe",
    "insName": "Naim",
    "email": "instructor@gmail.com",
    "category": "Web Development",
    "seats": "5000",
    "rating": 4.5,
    "oldPrice": 49.99,
    "newPrice": 29.99,
    "view": 1000,
    "lastUpdated": "2022-12-01",
    "duration": "5 hours 20 minutes",
    "status": "pending",
    "learningOutcomes": [
        "Create 20 Frontend Projects from Scratch",
        "Master Modern JavaScript (ES6+) including Arrows, Fetch, Promises, etc",
        "Effectively Manipulate the DOM and Handle Events",
        "Design Engaging Animations using CSS & JavaScript",
        "Retrieve and Process Data with Fetch & JSON from 3rd Party APIs",
        "Utilize HTML5 Canvas, Speech API, Audio, and Video Features"
    ],
    "classDetails": "Become a full-stack web developer with just one course. HTML, CSS, JavaScript, Node, React, MongoDB and more!"
},


  {
    img: "https://i.ibb.co/74KbM13/icon1-2.jpg",
    title: "JavaScript Fundamentals",
    name: "Jane Smith",
    insName: "Naim",
    email: "instructor@gmail.com",
    category: "Web Development",
    seats: "500",
    rating: 4.8,
    oldPrice: 59.99,
    newPrice: 39.99,
    view: 1500,
    updateDate: "2023-01-15",
    time: "3h 15m",
    status: "pending",
    classDetails:
      "Become a full-stack web developer with just one course. HTML, CSS, JavaScript, Node, React, MongoDB and more!",
  },

  {
    img: "https://i.ibb.co/pvP97QN/icon1-3.jpg",
    title: "Responsive Web Design",
    name: "Michael Johnson",
    insName: "Naim",
    email: "instructor@gmail.com",
    category: "Apps Development",
    seats: "560",
    rating: 4.7,
    oldPrice: 39.99,
    newPrice: 24.99,
    view: 800,
    updateDate: "2022-11-18",
    time: "2h 45m",
    status: "pending",
    classDetails:
      "Learn how to create responsive and mobile-friendly websites using CSS media queries and flexible layouts.",
  },

  {
    img: "https://i.ibb.co/LNXkG10/icon1-4.jpg",
    title: "Python Programming",
    name: "Sarah Thompson",
    insName: "Naim",
    email: "instructor@gmail.com",
    category: "Apps Development",
    seats: "5000",
    rating: 4.9,
    oldPrice: 69.99,
    newPrice: 49.99,
    view: 2000,
    updateDate: "2023-03-05",
    time: "4h 30m",
    status: "pending",
    classDetails:
      "Dive into Python programming and explore its vast applications in web development, data analysis, and more.",
  },

  {
    img: "https://i.ibb.co/0rLfmtY/icon1-5.jpg",
    title: "React.js Crash Course",
    name: "David Wilson",
    insName: "Naim",
    email: "instructor@gmail.com",
    category: "Apps Development",
    seats: "0",
    rating: 4.6,
    oldPrice: 49.99,
    newPrice: 34.99,
    view: 1200,
    updateDate: "2023-02-10",
    time: "3h 30m",
    status: "pending",
    classDetails:
      "Get up to speed with React.js and build dynamic and interactive user interfaces for your web applications.",
  },

  {
    img: "https://i.ibb.co/Nx8TT9S/icon1-6.jpg",
    title: "Node.js Essentials",
    name: "Emily Davis",
    insName: "Naim",
    email: "instructor@gmail.com",
    category: "Apps Development",
    seats: "5000",
    rating: 4.8,
    oldPrice: 59.99,
    newPrice: 44.99,
    view: 900,
    updateDate: "2022-10-25",
    time: "3h 15m",
    status: "pending",
    classDetails:
      "Learn the essentials of Node.js and leverage its powerful features for building scalable and efficient web applications.",
  },

  {
    img: "https://i.ibb.co/DwpP0ZR/icon1-12.jpg",
    title: "HTML5 and CSS3 Mastery",
    name: "Robert Brown",
    insName: "Naim",
    email: "instructor@gmail.com",
    category: "Apps Development",
    seats: "5000",
    rating: 4.7,
    oldPrice: 39.99,
    newPrice: 29.99,
    view: 1100,
    updateDate: "2022-12-15",
    time: "2h 45m",
    status: "pending",
    classDetails:
      "Master the latest features of HTML5 and CSS3 to create modern and visually appealing web pages.",
  },

  {
    img: "https://i.ibb.co/zQGgTcb/icon1-7.jpg",
    title: "Data Structures and Algorithms",
    name: "Jessica Lee",
    insName: "Naim",
    email: "instructor@gmail.com",
    category: "Apps Development",
    seats: "5000",
    rating: 4.9,
    oldPrice: 79.99,
    newPrice: 59.99,
    view: 1800,
    updateDate: "2023-04-20",
    time: "5h 0m",
    status: "pending",
    classDetails:
      "Learn fundamental data structures and algorithms that are essential for efficient programming and problem-solving.",
  },
];
